# -*- coding: utf-8 -*-
"""Публичный data/service API базового редактора однолинейных схем."""

from .controller import (
    AddedElement,
    AddedNode,
    BranchAttachmentEditResult,
    ClipboardLineGroup,
    ConfirmedLineLengthResult,
    ConnectionCompatibility,
    ConnectionEditResult,
    DeleteResult,
    EditorCommandError,
    LineTapConnectionEditResult,
    NewNodeTarget,
    NodeTarget,
    PasteResult,
    PhysicalLineEditResult,
    PhysicalLineInput,
    PortTarget,
    ProjectClipboard,
    ProjectEditorController,
    RecloserEditResult,
    RemoveSeriesEquipmentEditResult,
    RemoveRecloserEditResult,
    RemoveTapEditResult,
    SplitPhysicalLineEditResult,
    SeriesEquipmentEditResult,
    TapEditResult,
)
from .history import (
    ProjectChangeSet,
    ProjectCommandExecution,
    ProjectCommandHistory,
    ProjectHistoryEntry,
    ProjectHistoryError,
    ProjectHistoryEvent,
)
from .placement import EquipmentPlacementKind, EquipmentPlacementRegistry
from .state import EditorMode, EditorWorkspaceState, RepresentationGraphics
from .strings import RU_STRINGS, tr
from .tool_state import (
    EditorTool,
    EditorToolSnapshot,
    EditorToolStateMachine,
    EditorToolTransition,
)


__all__ = [
    "AddedElement",
    "AddedNode",
    "BranchAttachmentEditResult",
    "ClipboardLineGroup",
    "ConfirmedLineLengthResult",
    "ConnectionCompatibility",
    "ConnectionEditResult",
    "DeleteResult",
    "EditorCommandError",
    "EditorMode",
    "EditorTool",
    "EditorToolSnapshot",
    "EditorToolStateMachine",
    "EditorToolTransition",
    "EditorWorkspaceState",
    "EquipmentPlacementKind",
    "EquipmentPlacementRegistry",
    "LineTapConnectionEditResult",
    "NewNodeTarget",
    "NodeTarget",
    "PasteResult",
    "PhysicalLineEditResult",
    "PhysicalLineInput",
    "PortTarget",
    "ProjectChangeSet",
    "ProjectClipboard",
    "ProjectCommandExecution",
    "ProjectCommandHistory",
    "ProjectEditorController",
    "ProjectHistoryEntry",
    "ProjectHistoryError",
    "ProjectHistoryEvent",
    "RecloserEditResult",
    "RemoveSeriesEquipmentEditResult",
    "RemoveRecloserEditResult",
    "RemoveTapEditResult",
    "RU_STRINGS",
    "RepresentationGraphics",
    "SplitPhysicalLineEditResult",
    "SeriesEquipmentEditResult",
    "TapEditResult",
    "tr",
]
