"""Build a separate, explicitly synthetic four-voltage training project.

Import/build_project writes nothing. CLI requires a NEW --output path.
Existing projects and the oilfield demo are never regenerated by this tool.
"""
from __future__ import annotations

import argparse
from dataclasses import replace
import json
import math
from pathlib import Path
import sys
from tempfile import NamedTemporaryFile

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))

from tools.build_oilfield_demo import _Builder
from rza_calc.adapters import import_legacy_network
from rza_calc.core.methodology import Methodology
from rza_calc.core.model import GRID, GeneratorBranch, LineBranch, Mode, ProtectionSettings, TieBranch, TransformerBranch
from rza_calc.domain import ProjectStructure
from rza_calc.domain.diagram import DiagramDocument, DiagramDocumentId, RouteAnchorKind
from rza_calc.domain.electrical import thaw_json
from rza_calc.domain.history import ElectricalModelMemento
from rza_calc.domain.operating_parameters import OperatingParameters, with_operating_parameters
from rza_calc.io.project import FORMAT_VERSION, ProjectData, save_project

NAME = "УЧЕБНАЯ СХЕМА · ГТЭС — 110 / 35 / 10 / 0,4 кВ"
SOURCE = "Принятое учебное допущение build_compact_demo v1; не паспорт и не измерение"
WARNING = (
    "УСЛОВНАЯ УЧЕБНАЯ СХЕМА, НЕ РЕАЛЬНЫЙ ОБЪЕКТ. Подтверждение расчётных "
    "параметров означает только фиксацию принятого учебного набора для проверки "
    "программы. Паспортные и натурные данные не проверены. Уставки защит не заданы."
)
FACILITY_IDS = ("train_gtes", "train_cp", "train_ps", "train_ktp")
MODE_IDS = ("normal_max", "single_generator_min", "repair_ps_t1", "parallel_cp35")


def _provenance(keys, *, confirmed):
    return {key: {"source": SOURCE, "confirmation": "confirmed" if confirmed else "unconfirmed",
                  "origin": "assumption"} for key in keys}


def _sequence_data(builder):
    """Explicit physical ohms; transformer equivalents derived from synthetic ratings."""
    net = builder.net
    rows = []
    for node in net.nodes.values():
        node.calculation_base_kv = node.prefault_voltage_kv = node.u_nom
    for branch in net.branches.values():
        branch.note = WARNING
        branch.prot = ProtectionSettings(mtz=False, to=False, ozz=False,
                                         backup_through_transformer=False)
        branch.parameter_provenance = _provenance(
            (["ct_primary_a", "ct_secondary_a", "ct_port"] if branch.ct_ratio is not None else [])
            + (["breaker_t_off"] if branch.breaker_t_off is not None else []),
            confirmed=False,
        )
        if isinstance(branch, TieBranch):
            continue  # Ideal switching connectivity, not a guessed sequence impedance.
        if isinstance(branch, GeneratorBranch):
            branch.r2_ohm, branch.x2_ohm = .16, 1.8
            # Stator Z0=.10+j.50; neutral Zn=.20+j.05; total includes 3Zn.
            branch.r0_ohm, branch.x0_ohm = .70, .65
            branch.sequence_reference_kv = 10.
            branch.zero_sequence_connection = "series"
            keys = ("s_nom", "p_nom", "cos_phi", "u_nom", "xd2", "r_pu",
                    "r2_ohm", "x2_ohm", "r0_ohm", "x0_ohm", "sequence_reference_kv",
                    "zero_sequence_connection")
        elif isinstance(branch, TransformerBranch):
            facility = next(row for row in builder.facilities if branch.id in row['branch_ids'])
            kind = facility['kind']
            reference = branch.u_lv if kind == 'ktp' else branch.u_hv
            z1 = 10 * branch.uk * reference ** 2 / branch.s_nom
            r1 = 1000 * branch.p_k * reference ** 2 / branch.s_nom ** 2
            x1 = math.sqrt(z1 ** 2 - r1 ** 2)
            branch.r2_ohm, branch.x2_ohm = r1, x1
            # Adopted zero network, not something inferred from the nameplate.
            # Grounded transformer neutrals are ideal Zn=0 in this fixture.
            branch.r0_ohm, branch.x0_ohm = r1, .9 * x1
            branch.sequence_reference_kv = reference
            branch.group = {'gtes': 'YNd11', 'ktp': 'Dyn11'}.get(kind, 'YNyn0')
            branch.zero_sequence_connection = {'gtes': 'from_ground', 'ktp': 'to_ground'}.get(kind, 'series')
            branch.sequence_phase_shift_deg = 30. if kind in {'gtes', 'ktp'} else 0.
            keys = ("s_nom", "u_hv", "u_lv", "uk", "p_k", "group", "r2_ohm", "x2_ohm",
                    "r0_ohm", "x0_ohm", "sequence_reference_kv", "zero_sequence_connection",
                    "sequence_phase_shift_deg")
        elif isinstance(branch, LineBranch):
            branch.r2_ohm_per_km, branch.x2_ohm_per_km = branch.r0, branch.x0
            branch.r0_ohm_per_km, branch.x0_ohm_per_km = 3 * branch.r0, 3 * branch.x0
            branch.zero_sequence_connection = 'series'
            keys = ("length_mm", "r1_ohm_per_km", "x1_ohm_per_km", "parallel_count", "r2_ohm_per_km", "x2_ohm_per_km",
                    "r0_ohm_per_km", "x0_ohm_per_km", "zero_sequence_connection")
        else:
            raise TypeError(type(branch).__name__)
        branch.parameter_provenance.update(_provenance(keys, confirmed=True))
        rows.append({"branch_id": branch.id, "kind": branch.kind,
                     "reference_kv": branch.sequence_reference_kv,
                     "zero_connection": branch.zero_sequence_connection,
                     "phase_shift_deg": branch.sequence_phase_shift_deg})
    for load in net.loads.values():
        load.parameter_provenance = _provenance(("p_kw", "cos_phi", "k_use", "k_szp", "motor_share"), confirmed=False)
    return rows


def build_data():
    builder = _Builder()
    builder.net.name = NAME
    builder.net.neutral = {"110": "earthed", "35": "earthed", "10": "earthed", "0.4": "earthed"}
    plant = builder.facility('train_gtes', 'Учебная ГТЭС 110/10 кВ', 'gtes', 110, 10)
    builder.transformer_pair(plant, kva=10000, uk=10, loss=60)
    for section in (1, 2):
        gid = f'train_g{section}'
        terminal = builder.node(plant, gid+'_terminal', f'ГТГ-{section}, вывод 10 кВ', 10)
        bus = plant['buses']['lv'][section-1]
        builder.branch(plant, GeneratorBranch(gid, f'ГТГ-{section} 6 МВт (учебный)', GRID, terminal,
            s_nom=7500, p_nom=6, cos_phi=.8, u_nom=10, xd2=.15, r_pu=.012,
            ct_ratio=(600, 5), ct_node=terminal, switchable=False))
        breaker = builder.breaker(plant, gid+'_q', f'QF ГТГ-{section}', terminal, bus)
        plant['generators'].append({'id': gid, 'section': section, 'breaker': breaker, 'bus': bus,
                                   'node_ids': [terminal, bus], 'branch_ids': [gid, breaker]})
    cp = builder.facility('train_cp', 'Учебный ЦП 110/35 кВ', 'central', 110, 35, 'train_gtes')
    builder.transformer_pair(cp, kva=10000, uk=10, loss=60)
    builder.incoming_pair(cp, km=8.)
    ps = builder.facility('train_ps', 'Учебная ПС 35/10 кВ', 'substation', 35, 10, 'train_cp')
    builder.transformer_pair(ps, kva=4000, uk=8, loss=32)
    builder.incoming_pair(ps, km=3.)
    ktp = builder.facility('train_ktp', 'Учебная КТП 10/0,4 кВ', 'ktp', 10, .4, 'train_ps')
    builder.transformer_pair(ktp, kva=1000, uk=6, loss=10.5)
    builder.incoming_pair(ktp, km=.7)
    for row, power in ((plant, 80), (cp, 20), (ps, 300), (ktp, 90)):
        for section in (1, 2):
            builder.load_feeder(row, section, 1, f"{row['id'].removeprefix('train_').upper()} нагрузка-{section}", power)
    net = builder.net
    net.add_mode(Mode(MODE_IDS[0], 'Учебный: нормальная схема MAX', system='max',
        description='По одному ГТГ на независимую секцию; все СВ открыты.'))
    net.add_mode(Mode(MODE_IDS[1], 'Учебный: один ГТГ MIN', system='min',
        states={'train_g2_q': False, plant['bus_ties']['lv']: True}, availability={'train_g2': False},
        description='ГТГ-2 выведен, его QF открыт; СВ 10 кВ ГТЭС замкнут. MIN меняет также сопротивление линий по методике; перегрузка не проверяется.'))
    t1 = ps['transformers'][0]
    net.add_mode(Mode(MODE_IDS[2], 'Учебный: ремонт Т1 ПС', system='min',
        states={t1['hv_breaker']: False, t1['lv_breaker']: False, ps['bus_ties']['lv']: True},
        availability={t1['id']: False}, description='Т1 ПС недоступен, оба QF открыты; СВ 10 кВ ПС питает обе секции от Т2.'))
    net.add_mode(Mode(MODE_IDS[3], 'Учебный: параллель через СВ 35 кВ ЦП', system='max',
        states={cp['bus_ties']['lv']: True}, description='Замкнут только СВ 35 кВ ЦП: две питающие цепи и два ГТГ соединены. Допущено согласование ЭДС; синхронизация и потоки мощности не рассчитываются.'))
    equivalents = _sequence_data(builder)
    manifest = {
        'schema_version': 1, 'name': NAME, 'demo_only': True, 'warning': WARNING,
        'source': SOURCE, 'facilities': builder.facilities, 'mode_ids': list(net.modes),
        'normal_mode_id': MODE_IDS[0], 'generator_power_mw': 12,
        'physical_inputs_status': 'conditional_training_inputs_not_nameplate_verified',
        'sequence_equivalents': equivalents,
        'assumptions': [
            'Явные расчётные базы и предаварийные линейные напряжения равны номинальным 110/35/10/0,4 кВ.',
            'ГТГ: Z2=0,16+j1,80 Ом; Z0=(0,10+j0,50)+3*(0,20+j0,05)=0,70+j0,65 Ом на 10 кВ.',
            'GSU YNd11: заземление со стороны ВН, Z0-шунт from_ground; CP/PS YNyn0: принятый последовательный Z0; KTP Dyn11: Z0-шунт to_ground.',
            'У трансформаторов Z2=Z1 по условным uk/потерям, Z0=R1+j0,9X1, Zn=0. Это отдельное допущение, не следствие одной группы соединения.',
            'Линии: Z2=Z1 и Z0=3Z1 на километр. Нулевой эквивалент включает весь принятый путь возврата; ёмкости не заданы.',
            'Нагрузки не подпитывают КЗ. Потребители ГТЭС и ЦП — эквиваленты на соответствующих шинах без отдельных ТСН.',
            'ТТ/время отключения унаследованы как неподтверждённые учебные поля. МТЗ/ТО/ОЗЗ отключены на всех ветвях.',
        ],
        'limits': ['Нет потокораспределения, допустимости резервной нагрузки, синхронизации, динамики, пуска двигателей или подбора/проверки защит.',
                   'Разрешение параллели относится только к этому учебному расчётному сценарию; не разрешение реальных переключений.'],
        'counts': {'facilities': 4, 'nodes': len(net.nodes), 'branches': len(net.branches), 'loads': len(net.loads),
                   'generators': 2, 'transformers': 8, 'breakers': sum(isinstance(b, TieBranch) for b in net.branches.values()),
                   'lines': sum(isinstance(b, LineBranch) for b in net.branches.values()), 'modes': 4},
    }
    return net, manifest


def build_project(*, with_layout=True):
    net, manifest = build_data()
    model = import_legacy_network(net)
    snapshot = ElectricalModelMemento.capture(model)
    equipment = {}
    for eid, item in model.equipment.items():
        legacy_id = item.extensions.get('legacy_calculation', {}).get('legacy_id')
        obj = net.branches.get(legacy_id) or net.loads.get(legacy_id)
        extension = thaw_json(item.extensions)
        if obj is not None and obj.parameter_provenance:
            extension['rza_calc.parameter_provenance'] = obj.parameter_provenance
        equipment[eid] = replace(item, extensions=extension)
    states = {sid: replace(state, extensions=with_operating_parameters(state.extensions,
                OperatingParameters(parallel_operation=True))) for sid, state in model.operating_states.items()}
    model = replace(snapshot, equipment=equipment, operating_states=states).to_model()
    methodology = Methodology.load()
    project = ProjectData(net, methodology,
        {'name': NAME, 'object': 'Условный учебный объект', 'note': WARNING, '_warning': WARNING, 'training_demo': manifest},
        ProjectStructure(), FORMAT_VERSION, model, methodology_ref=methodology.data,
        diagram=DiagramDocument(DiagramDocumentId('diagram.compact-training'), NAME))
    # The DTO initially predates the explicitly added canonical provenance/modes.
    project.refresh_calculation_view(force=True)
    if with_layout:
        from tools.oilfield_layout import build_layout
        from rza_calc.editor.bus_connections import endpoint_fraction
        diagram = build_layout(project, manifest)
        routes = {}
        for rid, route in diagram.routes.items():
            updates = {}
            for key, anchor, point in (('start_anchor', route.start_anchor, route.waypoints[0]),
                                       ('end_anchor', route.end_anchor, route.waypoints[-1])):
                if anchor.kind is RouteAnchorKind.BUS:
                    rep = diagram.representations[anchor.representation_id]
                    graphics = rep.extensions['stage3_graphics']
                    fraction = endpoint_fraction(rep, graphics['width'], graphics['height'], anchor, point)
                    updates[key] = replace(anchor, anchor_key=format(fraction, '.17g'))
            routes[rid] = replace(route, **updates)
        project.diagram = replace(diagram, routes=routes, name='Учебная схема · четыре ступени напряжения')
    return project


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True, help='NEW JSON file; existing files are never overwritten')
    args = parser.parse_args(argv)
    target = args.output.expanduser().resolve()
    if target.exists():
        parser.error(f'Output already exists: {target}')
    project = build_project()
    target.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile(prefix='.compact-', suffix='.json', dir=target.parent, delete=False) as stream:
        temporary = Path(stream.name)
    try:
        save_project(temporary, project)
        data = temporary.read_bytes()
        with target.open('xb') as stream:
            stream.write(data)
    finally:
        temporary.unlink(missing_ok=True)
    print(json.dumps(project.metadata['training_demo']['counts'], ensure_ascii=False))
    print(target)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
