# -*- coding: utf-8 -*-
"""Public Stage-2 electrical topology API."""

from .engine import (
    ConcurrentTopologyMutationError,
    NORMAL_STATE,
    NormalStateSelection,
    StateSelection,
    TopologyEngine,
    TopologyInputError,
    electrical_model_identity,
)
from .handlers import (
    BehaviorKind,
    TopologyBehaviorHandler,
    TopologyBehaviorRegistry,
    builtin_topology_handlers,
)
from .model import (
    Conductivity,
    DiagnosticSeverity,
    Energization,
    FeederView,
    ResolvedOperatingState,
    ResolvedPosition,
    SourceKind,
    StateOrigin,
    TopologyCompilationError,
    TopologyCompatibilityError,
    TopologyComponent,
    TopologyComponentId,
    TopologyDiagnostic,
    TopologyError,
    TopologyLink,
    TopologyLinkId,
    TopologyNeighbor,
    TopologyPath,
    TopologyPathStep,
    TopologyQueryError,
    TopologySnapshot,
    TopologySource,
    VoltageEvidence,
    VoltageResolution,
    VoltageStatus,
    VoltageZone,
    VoltageZoneId,
)

__all__ = [
    "BehaviorKind",
    "ConcurrentTopologyMutationError",
    "Conductivity",
    "DiagnosticSeverity",
    "Energization",
    "FeederView",
    "NORMAL_STATE",
    "NormalStateSelection",
    "ResolvedOperatingState",
    "ResolvedPosition",
    "SourceKind",
    "StateOrigin",
    "StateSelection",
    "TopologyBehaviorHandler",
    "TopologyBehaviorRegistry",
    "TopologyCompilationError",
    "TopologyCompatibilityError",
    "TopologyComponent",
    "TopologyComponentId",
    "TopologyDiagnostic",
    "TopologyEngine",
    "TopologyError",
    "TopologyInputError",
    "TopologyLink",
    "TopologyLinkId",
    "TopologyNeighbor",
    "TopologyPath",
    "TopologyPathStep",
    "TopologyQueryError",
    "TopologySnapshot",
    "TopologySource",
    "VoltageEvidence",
    "VoltageResolution",
    "VoltageStatus",
    "VoltageZone",
    "VoltageZoneId",
    "builtin_topology_handlers",
    "electrical_model_identity",
]
